# Generated by Django 5.0.1 on 2024-01-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Comp_Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.CharField(max_length=30)),
                ('path_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.CharField(max_length=30)),
                ('path_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.CharField(max_length=30)),
                ('path_img', models.TextField()),
            ],
        ),
    ]
